version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: dbxyz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - dbxyz

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/dbxyz?sslmode=disable
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - dbxyz
    volumes:
      - ./api:/app
    command: go run cmd/server/main.go

volumes:
  postgres_data:

networks:
  dbxyz: